#!/bin/bash

DOCKER_IMAGE=alectolytic/rpmbuilder
COPR_REPOSITORY=repository
OS_ARCH=x86_64
OS_TYPE=centos
OS_DIST=epel
OS_VERSION=7

docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}